services:
  # app:
  #   container_name: app
  #   build: 
  #     context: ./app
  #     dockerfile: Dockerfile
  #   env_file:
  #     - ./app/.env
  #   ports: 
  #     - "3000:3000"
  #   networks:
  #     - sharding_example_network 
  #   volumes:
  #     - ./app:/home/app/node # Mount code directory
  #     - /home/app/node/node_modules  # Prevent overwriting node_modules

  partition_pg_store:
    image: postgres:16
    container_name: store_main
    environment:
      POSTGRES_USER: marcus
      POSTGRES_PASSWORD: marcus
      POSTGRES_DB: store
    ports:
      - "5432:5432"
    volumes:
      - partition_data:/var/lib/postgresql/data
    networks:
      - sharding_example_network
    profiles:
      - partition
  
  store_main:
    image: postgres:16
    container_name: store_main
    environment:
      POSTGRES_USER: marcus
      POSTGRES_PASSWORD: marcus
      POSTGRES_DB: store
    ports:
      - "5432:5432"
    volumes:
      - store_main_data:/var/lib/postgresql/data
      - ./postgresql/sharding/shard1-setup.sql:/docker-entrypoint-initdb.d/shard1-setup.sql
    networks:
      - sharding_example_network
    profiles:
      - sharding_fdw
    
  store_shard1:
    image: postgres:16
    container_name: store_shard1
    environment:
      POSTGRES_USER: marcus
      POSTGRES_PASSWORD: marcus
      POSTGRES_DB: store
    ports:
      - "5433:5432"
    volumes:
      - store_shard1_data:/var/lib/postgresql/data
      - ./postgresql/sharding/shard2-setup.sql:/docker-entrypoint-initdb.d/shard2-setup.sql
    networks:
      - sharding_example_network
    profiles:
      - sharding_fdw

  store_shard2:
    image: postgres:16
    container_name: store_shard2
    environment:
      POSTGRES_USER: marcus
      POSTGRES_PASSWORD: marcus
      POSTGRES_DB: store
    ports:
      - "5434:5432"
    volumes:
      - store_shard2_data:/var/lib/postgresql/data
      - ./postgresql/sharding/shard3-setup.sql:/docker-entrypoint-initdb.d/shard3-setup.sql
    networks:
      - sharding_example_network
    profiles:
      - sharding_fdw
    
  plproxy:
    build:
      context: ./
      dockerfile: Dockerfile.plproxy
    container_name: store_main
    environment:
      POSTGRES_USER: marcus
      POSTGRES_PASSWORD: marcus
      POSTGRES_DB: store
    ports:
      - "5432:5432"
    volumes:
      # - ./postgresql/plproxy/proxy.setup.sql:/docker-entrypoint-initdb.d/proxy.setup.sql
      - plproxy_store_main_data:/var/lib/postgresql/data
    networks:
      - sharding_example_network
    profiles:
      - plproxy

  plproxy_store_shard1:
    image: postgres:16
    container_name: plproxy_store_shard1
    environment:
      POSTGRES_USER: marcus
      POSTGRES_PASSWORD: marcus
      POSTGRES_DB: store
    ports:
      - "5433:5432"
    volumes:
      - store_plproxy_shard1_data:/var/lib/postgresql/data
      - ./postgresql/plproxy/shard.setup.sql:/docker-entrypoint-initdb.d/shard.setup.sql
    networks:
      - sharding_example_network
    profiles:
      - plproxy

  plproxy_store_shard2:
    image: postgres:16
    container_name: plproxy_store_shard2
    environment:
      POSTGRES_USER: marcus
      POSTGRES_PASSWORD: marcus
      POSTGRES_DB: store
    ports:
      - "5434:5432"
    volumes:
      - store_plproxy_shard2_data:/var/lib/postgresql/data
      - ./postgresql/plproxy/shard.setup.sql:/docker-entrypoint-initdb.d/shard.setup.sql
    networks:
      - sharding_example_network
    profiles:
      - plproxy
  
  plproxy_store_shard3:
    image: postgres:16
    container_name: plproxy_store_shard3
    environment:
      POSTGRES_USER: marcus
      POSTGRES_PASSWORD: marcus
      POSTGRES_DB: store
    ports:
      - "5435:5432"
    volumes:
      - store_plproxy_shard3_data:/var/lib/postgresql/data
      - ./postgresql/plproxy/shard.setup.sql:/docker-entrypoint-initdb.d/shard.setup.sql
    networks:
      - sharding_example_network
    profiles:
      - plproxy

volumes:
  partition_data:
  store_main_data:
  store_shard1_data:
  store_shard2_data:
  store_plproxy_main_data:
  store_plproxy_shard1_data:
  store_plproxy_shard2_data:
  store_plproxy_shard3_data:
  plproxy_store_main_data:

networks:
  sharding_example_network:
    driver: bridge