services:
  # app:
  #   container_name: app
  #   build: 
  #     context: ./app
  #     dockerfile: Dockerfile
  #   env_file:
  #     - ./app/.env
  #   ports: 
  #     - "3000:3000"
  #   networks:
  #     - app_network  
  #   volumes:
  #     - ./app:/home/app/node # Mount code directory
  #     - /home/app/node/node_modules  # Prevent overwriting node_modules

  partition_pg_store:
    image: postgres:latest
    container_name: partition_pg_store
    environment:
      POSTGRES_USER: marcus
      POSTGRES_PASSWORD: marcus
      POSTGRES_DB: store
    ports:
      - "5432:5432"
    volumes:
      - partition_data:/var/lib/postgresql/data
    networks:
      - sharding_example_network
    profiles:
      - native_partition
  
  store_main:
    image: postgres:latest
    container_name: store_main
    environment:
      POSTGRES_USER: marcus
      POSTGRES_PASSWORD: marcus
      POSTGRES_DB: store
    ports:
      - "5433:5432"
    volumes:
      - store_main_data:/var/lib/postgresql/data
      - ./postgresql/sharding/main-setup.sql:/docker-entrypoint-initdb.d/main-setup.sql
    networks:
      - sharding_example_network
    profiles:
      - sharding_fdw
    
  store_shard1:
    image: postgres:latest
    container_name: store_shard1
    environment:
      POSTGRES_USER: marcus
      POSTGRES_PASSWORD: marcus
      POSTGRES_DB: store
    ports:
      - "5434:5432"
    volumes:
      - store_shard1_data:/var/lib/postgresql/data
      - ./postgresql/sharding/shard1-setup.sql:/docker-entrypoint-initdb.d/shard1-setup.sql
    networks:
      - sharding_example_network
    profiles:
      - sharding_fdw

  store_shard2:
    image: postgres:latest
    container_name: store_shard2
    environment:
      POSTGRES_USER: marcus
      POSTGRES_PASSWORD: marcus
      POSTGRES_DB: store
    ports:
      - "5435:5432"
    volumes:
      - store_shard2_data:/var/lib/postgresql/data
      - ./postgresql/sharding/shard2-setup.sql:/docker-entrypoint-initdb.d/shard2-setup.sql
    networks:
      - sharding_example_network
    profiles:
      - sharding_fdw

volumes:
  partition_data:
  store_main_data:
  store_shard1_data:
  store_shard2_data:

networks:
  sharding_example_network:
    driver: bridge