services:
  partition_pg_store:
    image: postgres:16
    container_name: store_main
    environment:
      POSTGRES_USER: marcus
      POSTGRES_PASSWORD: marcus
      POSTGRES_DB: store
    ports:
      - "5432:5432"
    volumes:
      - ./postgresql/partitioning/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - sharding_example_network
    profiles:
      - partition
  
  store_main:
    image: postgres:16
    container_name: store_main
    environment:
      POSTGRES_USER: marcus
      POSTGRES_PASSWORD: marcus
      POSTGRES_DB: store
    ports:
      - "5432:5432"
    volumes:
      - ./postgresql/sharding/shard1-setup.sql:/docker-entrypoint-initdb.d/shard1-setup.sql
    networks:
      - sharding_example_network
    profiles:
      - sharding_fdw
    
  store_shard1:
    image: postgres:16
    container_name: store_shard1
    environment:
      POSTGRES_USER: marcus
      POSTGRES_PASSWORD: marcus
      POSTGRES_DB: store
    ports:
      - "5433:5432"
    volumes:
      - ./postgresql/sharding/shard2-setup.sql:/docker-entrypoint-initdb.d/shard2-setup.sql
    networks:
      - sharding_example_network
    profiles:
      - sharding_fdw

  store_shard2:
    image: postgres:16
    container_name: store_shard2
    environment:
      POSTGRES_USER: marcus
      POSTGRES_PASSWORD: marcus
      POSTGRES_DB: store
    ports:
      - "5434:5432"
    volumes:
      - ./postgresql/sharding/shard3-setup.sql:/docker-entrypoint-initdb.d/shard3-setup.sql
    networks:
      - sharding_example_network
    profiles:
      - sharding_fdw
    
  plproxy:
    build:
      context: ./
      dockerfile: Dockerfile.plproxy
    container_name: store_main
    environment:
      POSTGRES_USER: marcus
      POSTGRES_PASSWORD: marcus
      POSTGRES_DB: store
    ports:
      - "5432:5432"
    volumes:
      - ./postgresql/plproxy/proxy.setup.sql:/docker-entrypoint-initdb.d/proxy.setup.sql
    networks:
      - sharding_example_network
    profiles:
      - sharding_plproxy

  plproxy_store_shard1:
    image: postgres:16
    container_name: plproxy_store_shard1
    environment:
      POSTGRES_USER: marcus
      POSTGRES_PASSWORD: marcus
      POSTGRES_DB: store
    ports:
      - "5433:5432"
    volumes:
      - ./postgresql/plproxy/shard.setup.sql:/docker-entrypoint-initdb.d/shard.setup.sql
    networks:
      - sharding_example_network
    profiles:
      - sharding_plproxy

  plproxy_store_shard2:
    image: postgres:16
    container_name: plproxy_store_shard2
    environment:
      POSTGRES_USER: marcus
      POSTGRES_PASSWORD: marcus
      POSTGRES_DB: store
    ports:
      - "5434:5432"
    volumes:
      - ./postgresql/plproxy/shard.setup.sql:/docker-entrypoint-initdb.d/shard.setup.sql
    networks:
      - sharding_example_network
    profiles:
      - sharding_plproxy
  
  plproxy_store_shard3:
    image: postgres:16
    container_name: plproxy_store_shard3
    environment:
      POSTGRES_USER: marcus
      POSTGRES_PASSWORD: marcus
      POSTGRES_DB: store
    ports:
      - "5435:5432"
    volumes:
      - ./postgresql/plproxy/shard.setup.sql:/docker-entrypoint-initdb.d/shard.setup.sql
    networks:
      - sharding_example_network
    profiles:
      - sharding_plproxy

networks:
  sharding_example_network:
    driver: bridge